'use client';
import Head from 'next/head';
import ButtonInput from './components/child/shared/ButtonInput';

const Home = () => {
  const handleClick = () => {
    alert('Button Clicked!');
  };

  return (
    <div className="flex flex-col items-center justify-center min-h-screen bg-gray-100">
      <Head>
        <title>My Next.js App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="text-4xl font-bold mb-4">Welcome to My Next.js App</h1>
      <ButtonInput label="Click Me!" onClick={() => handleClick()}> Hit me!</ButtonInput>
    </div>
  );
};

export default Home;